# Change these first
owner: xettri # Your GitHub username
repo: uptime # The name of this repository

sites:
  - name: Bharat Rawat Website
    url: https://www.bharatrawat.com

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bharat Rawat Status
  introTitle: "Uptime Status for **bharatrawat.com**"
  introMessage: This page shows real-time uptime monitoring for **bharatrawat.com**, powered by [Upptime](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
